accounts/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views



app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(),name ='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('verified/',views.VerifyEmailView.as_view(),name ='verify'),
    path('sent/<int:pk>',views.SentView.as_view(),name ='sent_confirm'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),name ='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),name = 'password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name ='password_reset_complate'),
    path('activate/<uidb64>/<token>/',views.ActivateAccount.as_view(), name='activate'),
    # path('profile/', views.ProfileView.as_view(),name = 'profile')
    # path('user',views.userprofile,name='home')
]

islamic/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(template_name = 'base.html'),name = 'home'),
    path('index/',views.IndexView.as_view(template_name = 'index.html'),name = 'index'),#extra cloning template
    path('about/',views.AboutView.as_view(template_name = 'about.html'),name = 'about'),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('dashboard/',views.TestPage.as_view(),name = 'test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),

    path('thankyou/',views.Thanksbeingpart.as_view(),name='thankyou'),
    path('oauth/', include('social_django.urls', namespace='social')),  # <-- here

    path('videos/', include('videos.urls',namespace = 'videos')),
    path('notes/', include('notes.urls',namespace = 'notes')),

    # path('yes/',views.SomeListView.as_view(),name ='yes'),

    path('quiz/', include('quiz.urls',namespace='quiz')),

    # path('youtube/', include('django_youtube.urls')),
    #navbar stuff
    path('videos/',views.VideosView.as_view(template_name ='pages/videos.html'),name = 'videos')
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.urls import path 
from . import views

app_name = 'notes'

urlpatterns = [
    path ('create/',views.NotesCreateView.as_view(),name = 'notes_create'),
    path ('detail/<int:pk>',views.NotesDetailView.as_view(),name = 'notes_detail'),
    path('list/<str:username>',views.NotesListView.as_view(),name='notes_list'),
    path('delete/<int:pk>',views.NotesDeleteView.as_view(),name='notes_delete'),
    path('update/<int:pk>',views.NotesUpdateView.as_view(),name ='notes_update'),
]

quiz/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.urls import path

app_name = 'quiz'
urlpatterns = [

    #   path('',views.WeekListView.as_view(),'week')

    path('week/', views.home, name = 'home'),
    path('result', views.result, name = 'result'),
    path('<str:choice>', views.questions, name = 'questions'),
]

videos/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
    path('list/',views.VideosListView.as_view(),name ='videos_playlist'),
    path('list/<str:list_title>/',views.VideosModelListView.as_view(),name ='list_videos'),
]

templates/pages/base_stuff/navbar.html
<header class="main-header">
        <!-- Logo -->
        <a href="{%url 'test' %}" class="logo"><b>Believer</b></a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
             
              <!-- Notifications: style can be found in dropdown.less -->
             
              <!-- Tasks: style can be found in dropdown.less -->
             
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="{{ user.userprofile.avatar.url }}" class="user-image" alt="User Image"/>
                  <span class="hidden-xs">{{ user.username }}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="{{ user.userprofile.avatar.url }}" class="img-circle" alt="User Image" />
                    <h4>
                      <b>{{ user.username }}
                      <small>Member since {{ user.userprofile.create_date|date:"M,Y"}}</small>
                    </h4>
                  </li>
                  <!-- Menu Body -->
          
                  <!-- Menu Footer-->
                  <li class="user-footer">
                  
                    <div class="pull-right">
                      <a href="{% url 'thanks' %}" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>

templates/pages/base_stuff/sidebar.html
{% load static %}
  <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="{{ user.userprofile.avatar.url }}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
              <p>{{ user.username }}</p>

              <a href="#">{% if user.is_active %}<i class="fa fa-circle text-success"></i> Online {% else %}<i class="fa fa-circle text-danger"></i> Offline {% endif %}</a>
            </div>
          </div>
          <!-- search form -->
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header" style='font-weight: normal;'>MAIN NAVIGATION</li>
            <li class="active treeview">
              <a href="{% url 'test' %}">
                <i class="fa fa-dashboard"></i> <span style='font-weight: normal;'>Home</span> 
              </a>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-files-o"></i>
               <span style='font-weight: normal;'>Courses</span>
               </a>
            </li>
            <li>
              <a href="{% url 'videos:videos_playlist' %}">
                <i class="fa fa-th"></i> <span style='font-weight: normal;'>Videos</span> 
              </a>
            </li>

            <li class="active treeview">
              <a href="{%url 'notes:notes_create'%}">
                <i class="fa fa-pencil"> </i> <span style='font-weight: normal;'>Create Note</span> 
              </a>
            </li>
             <li class="active treeview">
              <a href="{%url 'notes:notes_list' user.username %}">
                <i class="fa fa-tasks"> </i> <span style='font-weight: normal;'>Your Notes</span> 
              </a>
            </li>
            <li class="treeview">
              <a href="{%url 'quiz:home'%}">
                <i class="fa fa-laptop"></i>
                <span style='font-weight: normal;'>Quiz</span>
              </a>  
            </li>
          {% if user.is_superuser %}
            <li class="treeview">
              <a href="{% url 'admin:index' %}">
                <i class="fa fa-edit"></i> <span style='font-weight: normal;'>Admin</span>
              </a>
            </li>
            {% endif %}

            <li class="treeview">
              <a href="{% url 'about' %}">
                <i class="fa fa-info"> </i> <span style='font-weight: normal;'>About</span>
              </a>
            </li>
        <li>
              <a href="{% url 'accounts:contact' %}">
                <i class="fa fa-calendar"></i> <span style='font-weight: normal;'>Contact</span>
              </a>
            </li>  
        </section>

templates/pages/base_stuff/to_do_list.html
  {% load static %}
  <link href="{% static 'bootstrap/css/bootstrap.css'%}" rel="stylesheet" type="text/css" />    
    <!-- FontAwesome 4.3.0 -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons 2.0.0 -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />    
    <!-- Theme style -->
    <link href="{% static 'dist/css/AdminLTE.css'%}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins 
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/skin-yellow.css'%}" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="{% static 'plugins/iCheck/flat/yellow.css'%}" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="{% static 'plugins/morris/morris.css'%}" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.css'%}" rel="stylesheet" type="text/css" />
    <!-- Date Picker -->
    <link href="{% static 'plugins/datepicker/datepicker3.css'%}" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="{% static 'plugins/daterangepicker/daterangepicker-bs3.css'%}" rel="stylesheet" type="text/css" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'%}" rel="stylesheet" type="text/css" />
    
              <div class="box box-primary">
                <div class="box-header">
                  <i class="ion ion-clipboard"></i>
                  <h3 class="box-title">To Do List</h3>
                  <div class="box-tools pull-right">
                    <ul class="pagination pagination-sm inline">
                      <li><a href="#">&laquo;</a></li>
                      <li><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">&raquo;</a></li>
                    </ul>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <ul class="todo-list">
                  {% for notes in notes_data %}
                    <li>
                      <!-- drag handle -->
                      <span class="handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <!-- checkbox -->
                      <input type="checkbox" value="" name=""/>
                      <!-- todo text -->
                      <span class="text">{{ notes.essay|truncatechars:20}}</span>
                      <!-- Emphasis label -->
                      <!-- General tools such as edit or delete-->
                      <div class="tools">
                        <i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>
                      </div>
                    </li>
                    {% endfor %}
                  </ul>
                </div><!-- /.box-body -->
                <div class="box-footer clearfix no-border">
                  <a href="{% url 'notes:notes_create' %}"> <button class="btn btn-default pull-right"><i class="fa fa-plus"></i>Add item</button></a>
                </div>
              </div><!-- /.box -->

               <!-- jQuery 2.1.3 -->
    <script src="{% static 'plugins/jQuery/jQuery-2.1.3.min.js'%}"></script>
    <!-- jQuery UI 1.11.2 -->
    <script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js'%}" type="text/javascript"></script>    
    <!-- Morris.js charts -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="{% static 'plugins/morris/morris.min.js'%}" type="text/javascript"></script>
    <!-- Sparkline -->
    <script src="{% static 'plugins/sparkline/jquery.sparkline.min.js'%}" type="text/javascript"></script>
    <!-- jvectormap -->
    <script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'%}" type="text/javascript"></script>
    <script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js'%}" type="text/javascript"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'plugins/knob/jquery.knob.js" type="text/javascript"></script>
    <!-- daterangepicker -->
    <script src="plugins/daterangepicker/daterangepicker.js'%}" type="text/javascript"></script>
    <!-- datepicker -->
    <script src="{% static 'plugins/datepicker/bootstrap-datepicker.js'%}" type="text/javascript"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'%}" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="{% static 'plugins/iCheck/icheck.min.js'%}" type="text/javascript"></script>
    <!-- Slimscroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js'%}" type="text/javascript"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.min.js'%}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js'%}" type="text/javascript"></script>

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'dist/js/pages/dashboard.js'%}" type="text/javascript"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js'%}" type="text/javascript"></script>

templates/pages/base_stuff/videos_list.html
<div class='container'>
<div class'container' > <p style ='text-align:center'>
{% include 'base/video_count.html' %}
{% block content %}
{% endblock content %}
</div>