accounts/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views



app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(),name ='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('verified/',views.VerifyEmailView.as_view(),name ='verify'),
    path('sent/<int:pk>',views.SentView.as_view(),name ='sent_confirm'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),name ='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),name = 'password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name ='password_reset_complate'),
    path('activate/<uidb64>/<token>/',views.ActivateAccount.as_view(), name='activate'),
    # path('profile/', views.ProfileView.as_view(),name = 'profile')
    # path('user',views.userprofile,name='home')
]

islamic/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(template_name = 'base.html'),name = 'home'),
    path('index/',views.IndexView.as_view(template_name = 'index.html'),name = 'index'),#extra cloning template
    path('about/',views.AboutView.as_view(template_name = 'about.html'),name = 'about'),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('dashboard/',views.TestPage.as_view(),name = 'test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),

    path('thankyou/',views.Thanksbeingpart.as_view(),name='thankyou'),
    path('oauth/', include('social_django.urls', namespace='social')),  # <-- here

    path('videos/', include('videos.urls',namespace = 'videos')),
    path('notes/', include('notes.urls',namespace = 'notes')),

    # path('yes/',views.SomeListView.as_view(),name ='yes'),

    path('quiz/', include('quiz.urls',namespace='quiz')),

    # path('youtube/', include('django_youtube.urls')),
    #navbar stuff
    path('videos/',views.VideosView.as_view(template_name ='pages/videos.html'),name = 'videos')
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.urls import path

app_name = 'quiz'
urlpatterns = [

    #   path('',views.WeekListView.as_view(),'week')

    path('week/', views.home, name = 'home'),
    path('result', views.result, name = 'result'),
    path('<str:choice>', views.questions, name = 'questions'),
]

accounts/models.py
from django.urls import reverse
from django.db import models
from django.contrib import auth
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from django.utils import timezone
# from django.contrib.auth.models import User
# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):
    # email = models.EmailField(("Email Address"), max_length=254)
    def __str__(self):
        return "@{}".format(self.username)

class UserProfile(models.Model):

    user = models.OneToOneField(auth.models.User, on_delete=models.CASCADE)
    # author = models.ForeignKey(Post, on_delete=models.CASCADE)
    avatar = models.ImageField(("Avatar"), upload_to='displays', default = 'default.png',height_field=None, width_field=None, max_length=None,blank = True)
    slug = models.SlugField(blank = True)
    create_date = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return f'{self.user.username} UserProfile'
    
    def save(self,*args, **kwargs):
        super(UserProfile,self).save(*args, **kwargs) #it will take data and save it

        dp = Image.open(self.avatar.path) #storing avatar in varible
        if dp.height >300 or dp.width >300:
            output_size =(300,300) #set anysize you want
            dp.thumbnail(output_size) 
            dp.save(self.avatar.path) #after resing it save it in data base in place of uploaded once by user

    def get_absolute_url(self):
        return reverse("userprofile_detail", kwargs={"pk": self.pk})

@receiver(post_save,sender=auth.models.User)
def create_profile(sender,instance,created,**kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save,sender=auth.models.User)
def save_profile(sender,instance,**kwargs):
    instance.userprofile.save()

class Contact(models.Model):

    from_user = models.EmailField(max_length=254)
    subject = models.CharField( max_length=150)
    message = models.TextField()
    to_user = models.EmailField( max_length=254)
    create_date = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.from_user

    def get_absolute_url(self):
        return reverse("accounts:sent_confirm", kwargs={"pk": self.pk})


# class Profile(models.Model):
#     user = models.OneToOneField(auth.models.User, on_delete=models.CASCADE)
#     email_confirmed = models.BooleanField(default=False)

# @receiver(post_save, sender=User)
# def update_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)

# class Code(models.Model):

#     def __str__(self):
#         return self.vcode

  

accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.core import validators
from .models import Contact
from django.core.mail import send_mail

User = get_user_model()

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ["username","email","password1","password2"]
        model = get_user_model()
        widgets ={
            'username' : forms.TextInput(attrs={'class':'form-control'}),
            'email' : forms.TextInput(attrs={'class':'form-control'}),
            'password1' : forms.TextInput(attrs={'class':'form-control'}),
            'password2' : forms.TextInput(attrs={'class':'form-control'}),
        }
    
    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError("Email is invalid")
        return email
    

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        # self.fields['email'].label = 'Email Address'


class ContactForm(forms.ModelForm):
    
    class Meta:
        model = Contact
        fields = ["from_user","to_user","subject","message",]
        widgets ={
            'from_user' : forms.TextInput(attrs={'class':'form-control'}),
            'to_user' : forms.TextInput(attrs={'class':'form-control'}),
            'subject' : forms.TextInput(attrs={'class':'form-control'}),
            'message' : forms.Textarea(attrs={'class':'form-control'}),
            }
        
    def clean_users(self):
        from_user = self.cleaned_data["from_user"]
        to_user = self.cleaned_data["to_user"]
        print('this is notice me',from_user)
        print('rhis is 2 notive me',to_user)
        if from_user.endswith('.com') and to_user.endswith('.com'):
            return from_user,to_user
        else:
            raise forms.ValidationError("Email is not correct")
        
   

# class UserUpdateForm(forms.ModelForm):
#     email = forms.EmailField(required=False)
#     class Meta:
#         fields = ["username","email"]




#  for code verifivcation
# class CodeForm(forms.ModelForm):
    
#     vcode = forms.IntegerField(required=True)
#     class Meta:
#         model = Code
#         fields = ("vcode",)

#     def __init__(self,*args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['vcode'].label = 'Verfication Code'

  

accounts/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from .forms import UserCreateForm
from django.views.generic import CreateView,TemplateView,View
from . import forms
from islamic import settings
from django.contrib.auth.models import User
from .forms import ContactForm
# email 
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from .tokens import account_activation_token

from django.contrib.auth import login
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.core.mail import send_mail
from django.contrib import messages

# import random
# user = User

# token = 3
class SignUp(CreateView):
    form_class = UserCreateForm
    template_name = 'accounts/signup.html'
        
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():

            user = form.save(commit=False)
            user.is_active = False # Deactivate account till it is confirmed
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate Your Believer Account'
            message = render_to_string('accounts/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)

            return redirect('accounts:verify')

        return render(request, self.template_name, {'form': form})

class VerifyEmailView(TemplateView):
    template_name = "accounts/verified.html"

 
class ActivateAccount(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, ('Your account have been confirmed.'))
            return redirect('accounts:login')
        else:
            messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))
            return redirect('home')



class ContactView(CreateView):
    template_name = "accounts/contact.html"
    form_class = ContactForm

    def form_valid(self, form,*args, **kwargs):

        from_user = self.request.user
        print(from_user)
        to_user = form.cleaned_data["to_user"]
        subject = form.cleaned_data["subject"]
        message = form.cleaned_data["message"]
        if form.is_valid:
            send_mail(
                subject,
                message,
                from_user,
                [to_user],
                fail_silently=False,
                )  
        
        return super(*args, **kwargs).form_valid(form)

class SentView(TemplateView):
    template_name = 'accounts/sent_confirm.html'   

   
   
        
 






# class ProfileView(TemplateView):
#     template_name = "accounts/userprofile.html"




# @login_required
# def userprofile(request):
#     u_form =UserUpdateForm
#     p_form = UserProfileForm()

#     context ={
#         'u_form':u_form,
#         'p_form' :p_form
#     }
#     return render(request,"accounts/userprofile.html")





    

accounts/templates/accounts/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/contact.html
{% extends 'pages/videos.html' %}
{% block content %}
<div class='container' style='padding-right: 15px;
    padding-left: 155px;
    margin-right: auto;
    margin-left: auto;'
    >

              
                
                  <h2 class="box-title">Compose New Message</h2>
                
                <div class="box-body" style='font-weight:normal'>
                  <form method ='POST' action="{%url 'accounts:contact'%}">
                    {{ form.as_p }}
                     {% csrf_token %} 
                    <input type='submit' class='btn btn-warning' value='Send'>
                  </form>
                  </div>
                  
                  
                
            
            </div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'change_base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="background">
<div class="login-form" >
    <form method="POST">
    {% csrf_token %}
        <h2 class="text-center">Log in</h2>  
        {% bootstrap_form form %}     
        <div class="form-group">
            <button type="submit" class="btn btn-warning btn-block">Log in</button>
        </div>
        <div class="clearfix">
            <label class="float-left form-check-label"><input type="checkbox"> Remember me</label>
            <a  href="{% url 'password_reset' %}" class="float-right"><span style='color:black;'>Forgot Password?</span></a>
        </div>        
    </form>
    <p class="text-center" ><a href="{% url 'accounts:signup'%}"><span style='color:black;'>Create an Account</sspan></a></p>
</div>
</div>
{% endblock  %}

accounts/templates/accounts/password_reset.html
{% extends 'change_base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class='container' style='margin-top:8px'>
<h1>Reset Password</h1>
<form method = 'POST'>
{% csrf_token %}
{% bootstrap_form form %}
<input type='submit' class='btn btn-success' style=" background-color: #cfb15f ; border-color: #cfb15f;" value = 'Request Reset Password'> 
</div>
{% endblock  %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'change_base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class='container' style='margin-top:20px'>
<p class='alert alert-info'>Your password is successfully changed<p> 
<p><strong><a href="{% url 'login' %}">Log In</a></strong></p>
</div>

{% endblock  %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'change_base.html' %}
{% load bootstrap3 %}
{% block content %}

<div class='container' style='margin-top:18px'>
{% if validlink %}
<h1>Reset Password</h1>

<form class='accounts' method = 'POST'>
{% csrf_token %}
{% bootstrap_form form %}
<input type='submit' class='btn btn-success' style=" background-color: #cfb15f ; border-color: #cfb15f;" value = 'Confirm'> 
{% else %}

<p class='alert alert-info' >The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>
<p><strong><a href ="{% url 'password_reset' %}">password reset.</strong></a></p>
{% endif %}
</div>
{% endblock  %}

accounts/templates/accounts/password_reset_done.html
{% extends 'change_base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class='container' style='margin-top:20px'>
<p class='alert alert-info'>Check Your email to reset your password!<p> 
</div>
{% endblock  %}

accounts/templates/accounts/sent_confirm.html
{% extends 'change_base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class='container' style='margin-top:20px'>
<p class='alert alert-info'>Your email is sent successfully. </p> 
</div>
{% endblock  %}

accounts/templates/accounts/signup.html
{% extends 'change_base.html' %}
{% load bootstrap3 %}
{% block content %}
<!-- <div style='background-color:#faefbb;'> -->
{% comment %} {% include 'snippets/signup/css.html' %} {% endcomment %}
   {% include 'snippets/signup/css.html' %}

<div class="register-box">
      <div class="register-logo">
        <a href="{% url 'home' %}"><b style='color: #ccb852;'>Believer</b></a>
      </div>

      <div class="register-box-body" style='background-color:#dfcb9a'>
        <p class="login-box-msg">Register a new membership</p>
        <form method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
        
          <div class="row">
            <div class="col-xs-8">    
              <div class="checkbox icheck">
                <label>
                  <input type="checkbox"> I agree to the <a href="#">terms</a>
                </label>
              </div>                        
            </div><!-- /.col -->
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
            </div><!-- /.col -->
          </div>
        </form>        

        <div class="social-auth-links text-center">
          <p>- OR -</p>
          <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using Facebook</a>
        </div>

        <a href="{% url 'accounts:login' %}" class="text-center">I already have a membership</a>
      </div><!-- /.form-box -->

    {% include 'snippets/signup/js.html' %}
</div>
{% endblock %}

accounts/templates/accounts/userprofile.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
    <div class="main main-raised " style='margin-top:20px;'>
		<div class="profile-content">
            <div class="container">
                <div class="row">
	                <div class="col-md-6 ml-auto mr-auto">
        	           <div class="profile">
	                        <div class="avatar">
	                           <p style='text-align:center;'> <img src="{{ user.profile.avatar.url }}" alt="Circle Image" class="img-raised rounded-circle img-fluid"></p>
	                        </div>
	                        <div class="name">
	                            <h3 class="title">{{ user.username }}</h3>
								<h6>Muslim</h6>
								<a href="#pablo" class="btn btn-just-icon btn-link btn-dribbble"><i class="fa fa-dribbble"></i></a>
                                <a href="#pablo" class="btn btn-just-icon btn-link btn-twitter"><i class="fa fa-twitter"></i></a>
                                <a href="#pablo" class="btn btn-just-icon btn-link btn-pinterest"><i class="fa fa-pinterest"></i></a>
	                        </div>
	                    </div>
    	            </div>
                </div>
                <div >
                    <p style='text-align:center;width: 70%;;margin-left:140px;'>An artist of considerable range, Chet Faker — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music, giving it a warm, intimate feel with a solid groove structure. </p>
                </div>
{% endblock  %}

accounts/templates/accounts/verified.html
{% extends 'change_base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class='container' style='margin-top:20px'>
<p class='alert alert-info'>Your Account is successfully created. </p> 
<p class='alert alert-info'>Please Confirm your email to complete registration.</p>
</div>
{% endblock  %}