islamic/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(template_name = 'base.html'),name = 'home'),
    path('index/',views.IndexView.as_view(template_name = 'index.html'),name = 'index'),#extra cloning template
    path('about/',views.AboutView.as_view(template_name = 'about.html'),name = 'about'),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('dashboard/',views.TestPage.as_view(),name = 'test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),

    path('thankyou/',views.Thanksbeingpart.as_view(),name='thankyou'),
    path('oauth/', include('social_django.urls', namespace='social')),  # <-- here

    path('videos/', include('videos.urls',namespace = 'videos')),
    path('notes/', include('notes.urls',namespace = 'notes')),

    # path('yes/',views.SomeListView.as_view(),name ='yes'),

    path('quiz/', include('quiz.urls',namespace='quiz')),

    # path('youtube/', include('django_youtube.urls')),
    #navbar stuff
    path('videos/',views.VideosView.as_view(template_name ='pages/videos.html'),name = 'videos')
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.urls import path 
from . import views

app_name = 'notes'

urlpatterns = [
    path ('create/',views.NotesCreateView.as_view(),name = 'notes_create'),
    path ('detail/<int:pk>',views.NotesDetailView.as_view(),name = 'notes_detail'),
    path('list/<str:username>',views.NotesListView.as_view(),name='notes_list'),
    path('delete/<int:pk>',views.NotesDeleteView.as_view(),name='notes_delete'),
    path('update/<int:pk>',views.NotesUpdateView.as_view(),name ='notes_update'),
]

quiz/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.urls import path

app_name = 'quiz'
urlpatterns = [

    #   path('',views.WeekListView.as_view(),'week')

    path('week/', views.home, name = 'home'),
    path('result', views.result, name = 'result'),
    path('<str:choice>', views.questions, name = 'questions'),
]

notes/models.py
from django.db import models
from django.contrib import auth
from django.urls import reverse
from django.utils import timezone
# Create your models here.
class Notes(models.Model):

    author = models.ForeignKey(auth.models.User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    essay = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("notes:notes_detail", kwargs={"pk": self.pk})

notes/forms.py
from django import forms 
from django.views.generic import CreateView,ListView,DetailView
from .models import Notes

class NotesForm(forms.ModelForm):
    
    class Meta:
        model = Notes
        fields = ("title","essay")

        widgets ={
            'title' :forms.TextInput(attrs={'class':'form-control'}),
            'essay':forms.Textarea(attrs={'class':'form-control'})
        }




    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].label = 'Title'
        self.fields['essay'].label = 'Text'

notes/views.py
from django.shortcuts import render,get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
# Create your views here.
from .models import Notes
from .forms import NotesForm
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import auth



class NotesListView(LoginRequiredMixin,ListView):
    login_url = '/accounts/login/'
    model = Notes
    template_name = 'notes/notes_list.html'
    context_object_name = 'notes_data'
    paginate_by = 15
    def get_queryset(self):
        user = get_object_or_404(auth.models.User, username=self.kwargs.get('username'))
        return Notes.objects.filter(author=user).order_by('-create_date')

class NotesCreateView(LoginRequiredMixin,CreateView):
    login_url = '/accounts/login/'
    form_class = NotesForm
    model = Notes
    template_name = "notes/notes_create.html"

    def form_valid(self, form,*args, **kwargs):
        form.instance.author = self.request.user
        return super(*args, **kwargs).form_valid(form)
    
    


class NotesDetailView(LoginRequiredMixin,DetailView):
    login_url = '/accounts/login/'
    model = Notes
    context_object_name = 'notes'
    
class NotesDeleteView(LoginRequiredMixin,DeleteView):
    login_url = '/accounts/login/'
    model = Notes
    success_url = reverse_lazy('notes:notes_list')

class NotesUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/accounts/login/'
    refirect_field_name ='notes/notes_detail.html'
    form_class = NotesForm
    model = Notes
    template_name = "notes/notes_create.html"

notes/templates/notes/notes_confirm_delete.html
{% extends "pages/videos.html" %}
{% block content %}
<form method="post">
<div class='container' style='padding-right: 15px;
    padding-left: 175px;
    margin-right: auto;
    margin-left: auto;'>
    {% csrf_token %}
    <h2>Are you sure you want to delete <b>"{{object}}"</b></h2>
    <input type="submit" class="btn btn-danger" value="Confirm">
</form>
</div>
{% endblock  %}

notes/templates/notes/notes_create.html
{% extends 'pages/videos.html' %}
{% block content %}
<div class='container' style='padding-right: 15px;
    padding-left: 155px;
    margin-right: auto;
    margin-left: auto;'>
<div class="background" style='font-weight: normal;'>
<div class="login-form" >
    <form method="POST">
    {% csrf_token %}
        <h2 class="text-center">Note</h2>  
        {{ form.as_p }}     
        <div class="form-group">
            <button type="submit" class="btn btn-warning btn-block">Save</button>
        </div>      
    </form>
</div>
</div></div>
 {% endblock content %}

notes/templates/notes/notes_detail.html
{% extends 'pages/videos.html' %}
{% block content %}
<div class='container' style ='margin-top:20px ;'>
<h1 style='text-align:center'>{{ notes.title }}</h1>
<p style='text-align:center;font-weight: normal;'><small >created: {{ notes.create_date|date:'d-M-Y :P'  }}</small></p>
</div><hr style="width: 80%;">
<div class='container' style ='padding-right: 15px;
    padding-left: 0px;
    margin-right: auto;
    margin-left: auto;'>
<div class='row'>
<div class='col'>
  
<h4 style=' text-align:center;font-weight: normal; '>{{ notes.essay|linebreaks }}</h4>
</div>
</div>
<a href="{% url 'notes:notes_delete' pk=notes.pk %}"> <button class="btn btn-#ccb852 pull-right" >Delete</button></a>

</div>

{% endblock content %}

notes/templates/notes/notes_list.html
{% extends 'pages/videos.html' %}
{% block content %}

<div class="container bootstrap snippets bootdey" style='padding-right: 15px;
    padding-left: 155px;
    margin-right: auto;
    margin-left: auto;'
    >
  <div class="row">
    {% for notes in notes_data %}
    
    <div class="col-4" style='font-weight: normal;' >
		<ul class="notes">
            <li>
                <div class="rotate-1 lazur-bg" style='margin-left:80px'>
                    <small>{{ notes.create_date|date:'d-M-Y :P'  }}</small>
                    {{forloop.counter}}
                    <h4>{{ notes.title }}</h4>  
                    <hr>
                    <p>{{ notes.essay|truncatechars:20|linebreaks}}<hr></p>
                   <a href="{% url 'notes:notes_delete' pk=notes.pk %}" class="text-danger pull-right"><i class="fa fa-trash-o " style='color:black'></i></a>
                    <a href="{% url 'notes:notes_detail' pk=notes.pk %}" class="text-danger pull-right"><i class="fa fa-fw fa-envelope" style='color:black'></i></a>
                    <a href="{% url 'notes:notes_update' pk=notes.pk %}" class="text-danger pull-right"><i class="fa fa-fw fa-pencil" style='color:black'></i></a>
                    </div>

            </li>
                    
               
        </ul>  
	</div>
    {% endfor %}
    </div>
      {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class ='btn btn-warning'href='?page=1'>first</a>
            <a class ='btn btn-warning'href="?page={{page_obj.previous_page_number}}">Previous</a>   
        {% endif %}
        
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num  %}
                <a class ='btn btn-warning'href="?page={{num}}">{{num}}</a>
            {% elif num > page_obj.number|add:'-1' and num < page_obj.number|add:'1' %}
                <a class ='btn btn-success'href="?page={{num}}">{{num}}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class ='btn btn-warning'href="?page={{page_obj.next_page_number}}">Next</a>
            <a class ='btn btn-warning'href="?page={{page_obj.paginator.num_pages}}">Last</a>   
        {% endif %}
    {% endif %}
</div>

{% endblock content %}