islamic/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(template_name = 'base.html'),name = 'home'),
    path('index/',views.IndexView.as_view(template_name = 'index.html'),name = 'index'),#extra cloning template
    path('about/',views.AboutView.as_view(template_name = 'about.html'),name = 'about'),
    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('dashboard/',views.TestPage.as_view(),name = 'test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),

    path('thankyou/',views.Thanksbeingpart.as_view(),name='thankyou'),
    path('oauth/', include('social_django.urls', namespace='social')),  # <-- here

    path('videos/', include('videos.urls',namespace = 'videos')),
    path('notes/', include('notes.urls',namespace = 'notes')),

    # path('yes/',views.SomeListView.as_view(),name ='yes'),

    path('quiz/', include('quiz.urls',namespace='quiz')),

    # path('youtube/', include('django_youtube.urls')),
    #navbar stuff
    path('videos/',views.VideosView.as_view(template_name ='pages/videos.html'),name = 'videos')
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.urls import path 
from . import views

app_name = 'notes'

urlpatterns = [
    path ('create/',views.NotesCreateView.as_view(),name = 'notes_create'),
    path ('detail/<int:pk>',views.NotesDetailView.as_view(),name = 'notes_detail'),
    path('list/<str:username>',views.NotesListView.as_view(),name='notes_list'),
    path('delete/<int:pk>',views.NotesDeleteView.as_view(),name='notes_delete'),
    path('update/<int:pk>',views.NotesUpdateView.as_view(),name ='notes_update'),
]

quiz/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.urls import path

app_name = 'quiz'
urlpatterns = [

    #   path('',views.WeekListView.as_view(),'week')

    path('week/', views.home, name = 'home'),
    path('result', views.result, name = 'result'),
    path('<str:choice>', views.questions, name = 'questions'),
]

videos/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
    path('list/',views.VideosListView.as_view(),name ='videos_playlist'),
    path('list/<str:list_title>/',views.VideosModelListView.as_view(),name ='list_videos'),
]

notes/models.py
from django.db import models
from django.contrib import auth
from django.urls import reverse
from django.utils import timezone
# Create your models here.
class Notes(models.Model):

    author = models.ForeignKey(auth.models.User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    essay = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("notes:notes_detail", kwargs={"pk": self.pk})

templates/about.html
{% extends 'change_base.html' %}
 {% block content %}
 <div style="margin-top: 8px;" class="container">
 <h2>About</h2>
 <p>About Us</p>


<div class="row">
 <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
   <img src="assets/img/about.jpg" class="img-fluid" alt="">
 </div>
 <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content">
   <h3>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h3>
   <p class="font-italic">
     Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
     magna aliqua.
   </p>
   <ul>
     <li><i class="icofont-check-circled"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
     <li><i class="icofont-check-circled"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
     <li><i class="icofont-check-circled"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>
   </ul>
   <p>
     Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
   </p>
 </div>
</div>
</div>
</section>
</div>


 {% endblock content %}
 

templates/change_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  
  <script src="{% static 'cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js'%}"></script>
  <link rel="stylesheet" href="{% static 'cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css'%}" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet" href="{% static 'signup/signup.css'%}" type="text/css" media="screen" charset="utf-8">

  <title>Believer</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">
  {% include 'base/css.html' %}
</head>

<body >
  {% include 'base/nav.html' %}
  
   <section id="about" class="about">
    {% block content %}

    {% endblock content %}
    </section>
    {% include 'base/js.html' %}
</body>
</html>

templates/test.html
<!DOCTYPE html>
{% load static %}
<html>
  <head> 
    <meta charset="UTF-8">
    <title>AdminLTE 2 | Dashboard</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{% static 'bootstrap/css/bootstrap.css'%}" rel="stylesheet" type="text/css" />    
    <!-- FontAwesome 4.3.0 -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons 2.0.0 -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />    
    <!-- Theme style -->
    <link href="{% static 'dist/css/AdminLTE.css'%}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins 
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/skin-yellow.css'%}" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="{% static 'plugins/iCheck/flat/yellow.css'%}" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="{% static 'plugins/morris/morris.css'%}" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.css'%}" rel="stylesheet" type="text/css" />
    <!-- Date Picker -->
    <link href="{% static 'plugins/datepicker/datepicker3.css'%}" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="{% static 'plugins/daterangepicker/daterangepicker-bs3.css'%}" rel="stylesheet" type="text/css" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'%}" rel="stylesheet" type="text/css" />
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="skin-blue">
    <div class="wrapper">
      {% include 'pages/base_stuff/navbar.html' %}
      {% include 'pages/base_stuff/sidebar.html' %}
      

        <!-- /.sidebar -->
   <section id="about" class="about">
  
      </aside>

      <!-- Right side column. Contains the navbar and content of the page -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Dashboard
            <small>Control panel</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <!-- Small boxes (Stat box) -->
          <div class="row">
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-aqua">
                <div class="inner">
                  <h3>{{ count }}</h3>
                  <p>Videos</p>
                </div>
                <div class="icon">
                  <i class="ion ion-bag"></i>
                </div>
                <a href="{% url 'videos:videos_playlist' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-green">
                <div class="inner">
                  <h3>{{quiz_count}}<sup style="font-size: 20px"></sup></h3>
                  <p>Total Quiz</p>
                </div>
                <div class="icon">
                  <i class="ion ion-stats-bars"></i>
                </div>
                <a href="{% url 'quiz:home' %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-yellow">
                <div class="inner">
                  <h3>{{request.user.notes_set.all.count}}</h3>
                  <p>Notes</p>
                </div>
                <div class="icon">
                  <i class="ion ion-person-add"></i>
                </div>
                <a href="{%url 'notes:notes_list' user.username %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-red">
                <div class="inner">
                  <h3>{{user_count}}</h3>
                  <p>Our Company</p>
                </div>
                <div class="icon">
                  <i class="ion ion-pie-graph"></i>
                </div>
                <a href="{% url 'thankyou'%}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
          </div><!-- /.row -->
          <!-- Main row -->
          <div class="row">
            <!-- Left col -->
      </div>
    </section>
            
               

              
     
  <footer class="main-footer" style=' position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   text-align: center;'>
        <div class="pull-right hidden-xs">
          <b>Islam</b> 2.0
        </div>
        <strong>Created in 2020 <a href="https://www.linkedin.com/in/ahmed-yasin-588b021b0/">Ahmed Yasin</a>.</strong> All rights reserved.
    </footer>
    

    <!-- jQuery 2.1.3 -->
    <script src="{% static 'plugins/jQuery/jQuery-2.1.3.min.js'%}"></script>
    <!-- jQuery UI 1.11.2 -->
    <script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js'%}" type="text/javascript"></script>    
    <!-- Morris.js charts -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="{% static 'plugins/morris/morris.min.js'%}" type="text/javascript"></script>
    <!-- Sparkline -->
    <script src="{% static 'plugins/sparkline/jquery.sparkline.min.js'%}" type="text/javascript"></script>
    <!-- jvectormap -->
    <script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'%}" type="text/javascript"></script>
    <script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js'%}" type="text/javascript"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'plugins/knob/jquery.knob.js" type="text/javascript"></script>
    <!-- daterangepicker -->
    <script src="plugins/daterangepicker/daterangepicker.js'%}" type="text/javascript"></script>
    <!-- datepicker -->
    <script src="{% static 'plugins/datepicker/bootstrap-datepicker.js'%}" type="text/javascript"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'%}" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="{% static 'plugins/iCheck/icheck.min.js'%}" type="text/javascript"></script>
    <!-- Slimscroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js'%}" type="text/javascript"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.min.js'%}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js'%}" type="text/javascript"></script>

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'dist/js/pages/dashboard.js'%}" type="text/javascript"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js'%}" type="text/javascript"></script>
  </body>
</html>

templates/thanks.html
{% extends 'change_base.html' %}
{% block content %}
<div class = 'container' style='margin-top:80px'>
<h1>Thanks for coming, Come back soon!</h1>
</div>
{% endblock content %}

templates/thankyoubeingpart.html
{% extends 'change_base.html' %}
 {% block content %}
 <div style="margin-top: 8px;" class="container">
 <h2 >Thank you being part of our Ismalic campany</h2>
 <p>We are happy that you join our company and willing to learn knowledge about Islam</p>


<div class="row">
 <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
   <img src="assets/img/about.jpg" class="img-fluid" alt="">
 </div>
 <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content">
   <h3>You are the member of believer family and we really appreciate this!</h3>
   <p class="font-italic">
     Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
     magna aliqua.
   </p>
   <ul>
     <li><i class="icofont-check-circled"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
     <li><i class="icofont-check-circled"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
     <li><i class="icofont-check-circled"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>
   </ul>
   <p>
     Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
   </p>
 </div>
</div>
</div>

</div>


 {% endblock content %}
 